apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: storywalkers-api
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "0"
        autoscaling.knative.dev/maxScale: "10"
    spec:
      containerConcurrency: 80
      timeoutSeconds: 60
      containers:
        - image: gcr.io/storywalkers-b4fdf/storywalkers-api:latest
          ports:
            - containerPort: 8080
          env:
            - name: ENV
              value: production
            - name: AUTH_REQUIRED
              value: "true"
            - name: FIREBASE_PROJECT_ID
              value: storywalkers-b4fdf
